using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

/*
* File name: Stats.cs
* 
* @description This class contains the primary fitness and health stats generated by the application.
* 
* 
* @author Michael Miller
* @email miller.7594@osu.edu
* @version 03/05/2017
* 
*/

namespace CAPLab
{

    public class Stats
    {
        public int Steps { get; set; }

        //TODO figure out what stats are and assign to this class where appropriate

        public Stats()
        {

        }

        public Stats(User user)
        {

        }
    }
}
