using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

//This page is to contain the specific eating stats generated by the app. 

namespace CAPLab
{
    class EatingStats : ContentPage
    {
        public EatingStats()
        {
            var placeholderText = new Label
            {
                Text = "This page is to contain the specific eating stats generated by the app."
            };
            Content = new StackLayout
            {
                Children =
                {
                    placeholderText
                }
            };
        }
    }
}
