using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;


/*
* File name: HomepageNav.cs
* 
* @description This class is the primary navigation/home page to other areas of the app. 
*              This page is to contain the stats pages generated by other portions of the app.
*              //Notes on implementation found at link: https://developer.xamarin.com/api/type/Xamarin.Forms.TabbedPage/ 
* 
* @author Michael Miller
* @email miller.7594@osu.edu
* @version 02/27/2017
* 
*/

namespace CAPLab
{
    class HomepageNav : TabbedPage
    {
        public HomepageNav()
        {
            //Moves settings page to a button on the toolbar. 
            // the second argument should be the name of an icon image file (PNG)
            ToolbarItems.Add( new ToolbarItem ("Settings", "settings", () =>
                {
                    Navigation.PushAsync(new Settings()); //Navigation.PushAsync(new Settings(App.user));
                }));

            //TODO: Make title bold.
            Title = "OSU CAPLab";
            


            BarBackgroundColor = Color.Red;

            Children.Add(new HomepageStats());

            Children.Add(new EatingStats());

            Children.Add(new ExerciseStats());

            Children.Add(new SurveyPage());
        }


    }
}
