using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

//This page is to contain the specific eating stats generated by the app. 

namespace CAPLab
{
    class EatingStats : ContentPage
    {
        public EatingStats()
        {
            Icon = "eating.png";
            var placeholderText = new Label
            {
                Text = "This page is to contain the specific eating stats generated by the app."
            };

            //placeholder boxes
            Label box1Label = new Label { Text = "Eating graph 1" };
            BoxView box1 = new BoxView
            {
                Color = Color.Gray
            };
            Label box2Label = new Label { Text = "Eating graph 2" };
            BoxView box2 = new BoxView
            {
                Color = Color.Gray
            };
            Label box3Label = new Label { Text = "Eating graph 3" };
            BoxView box3 = new BoxView
            {
                Color = Color.Gray
            };

            Content = new StackLayout
            {
                Children =
                {
                    placeholderText,
                    box1Label,
                    box1,
                    box2Label,
                    box2,
                    box3Label,
                    box3
                }
            };
        }
    }
}
