using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

/*
* File name: ExerciseStats.cs
* 
* @description This class exists to render and control the logic of the exercise stats page of the primary app. 
*              This page is to contain the specific exercise stats generated by the app. 
* 
* @author Michael Miller
* @email miller.7594@osu.edu
* @version 02/27/2017
* 
*/

namespace CAPLab
{
    class ExerciseStats : ContentPage
    {
        public ExerciseStats()
        {
            Icon = "exercise.png";
            var placeholderText = new Label
            {
                Text = "This page is to contain the specific exercise stats generated by the app."
            };

            //placeholder boxes
            Label box1Label = new Label {Text = "Exercise Graph 1" };
            BoxView box1 = new BoxView
            {
                Color = Color.Gray
            };

            Label box2Label = new Label { Text = "Exercise Graph 2" };
            BoxView box2 = new BoxView
            {
                Color = Color.Gray
            };
            Label box3Label = new Label { Text = "Exercise Graph 3" };
            BoxView box3 = new BoxView
            {
                Color = Color.Gray
            };

            Content = new StackLayout
            {
                Children =
                {
                    placeholderText,
                    box1Label,
                    box1,
                    box2Label,
                    box2,
                    box3Label,
                    box3
                }
            };
        }
    }
}
