using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

//This page is to contain the primary agregate stats generated by the app.

namespace CAPLab
{
    class HomepageStats : ContentPage
    {
        public HomepageStats()
        {
            Icon = "homeIcon.png";
            var placeholderText = new Label
            {
                Text = "This page is to contain the primary agregate stats generated by the app."
            };

            //placeholder boxes
            Label box1Label = new Label { Text = "Your steps here:" };
            BoxView box1 = new BoxView
            {
                Color = Color.Red
            };
            Label box2Label = new Label { Text = "Your Exercise goal progress here:" };
            BoxView box2 = new BoxView
            {
                Color = Color.Gray
            };
            Label box3Label = new Label { Text = "Your Diet goal progress here:" };
            BoxView box3 = new BoxView
            {
                Color = Color.Red
            };
            Content = new StackLayout
            {
                Children =
                {
                    placeholderText,
                    box1Label,
                    box1,
                    box2Label,
                    box2,
                    box3Label,
                    box3
                }
            };
        }
    }
}
